name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./FacialRecognitionLogin.Droid/FacialRecognitionLogin.Droid.csproj /verbosity:normal /p:Configuration=Release     
          
    Build_UITests:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build UITest Project
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./GitTrends.UITests/GitTrends.UITests.csproj   
  
    UnitTest_GitTrends:
      runs-on: macos-latest

      env:
        GetTestTokenApiKey: ${{ secrets.GetTestTokenApiKey }}
        GetAppCenterApiKeysKey: ${{ secrets.GetAppCenterApiKeysKey}}
        GetSyncFusionInformationApiKey: ${{ secrets.GetSyncFusionInformationApiKey }}
        GetNotificationHubInformationApiKey: ${{ secrets.GetNotificationHubInformationApiKey }}
        APPCENTER_SOURCE_DIRECTORY: .

      steps:
      - uses: actions/checkout@v1

      - name: Inject API Keys
        run: |
          chmod -R 777 ./GitTrends.Android/appcenter-pre-build.sh
          ./GitTrends.Android/appcenter-pre-build.sh
          
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name GitTrends.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject