name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Inject API Keys
        run: |
          AzureConstantsFile=`find . -name AzureConstants.cs`
          echo AzureConstantsFile $AzureConstantsFile

          sed -i '' 's/#Error/\/\/#Error/g' $AzureConstantsFile

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          msbuild ./FacialRecognitionLogin.Droid/FacialRecognitionLogin.Droid.csproj /verbosity:normal /p:Configuration=Release     
